INSERT INTO vehicles (brand, model, engine, manufacture_year, used) VALUES
    ('Volkswagen', 'Golf', 'diesel', 2015, TRUE),
    ('Volkswagen', 'Passat', 'diesel', 2016, FALSE),
    ('Volkswagen', 'Polo', 'oil', 2017, FALSE),
    ('Volkswagen', 'ID.3', 'electric', 2018, TRUE),
    ('Volkswagen', 'ID.4', 'electric', 2019, FALSE),
    ('Tesla', 'Model 3', 'electric', 2020, FALSE),
    ('Tesla', 'Model Y', 'electric', 2021, TRUE),
    ('Tesla', 'Model S', 'electric', 2022, FALSE),
    ('Tesla', 'Model X', 'electric', 2023, FALSE),
    ('Toyota', 'Corolla', 'oil', 2024, TRUE),
    ('Skoda', 'Octavia', 'diesel', 2025, FALSE),
    ('BMW', '320d', 'diesel', 2015, FALSE),
    ('Volkswagen', 'Golf', 'diesel', 2016, TRUE),
    ('Volkswagen', 'Passat', 'diesel', 2017, FALSE),
    ('Volkswagen', 'Polo', 'oil', 2018, FALSE),
    ('Volkswagen', 'ID.3', 'electric', 2019, TRUE),
    ('Volkswagen', 'ID.4', 'electric', 2020, FALSE),
    ('Tesla', 'Model 3', 'electric', 2021, FALSE),
    ('Tesla', 'Model Y', 'electric', 2022, TRUE),
    ('Tesla', 'Model S', 'electric', 2023, FALSE),
    ('Tesla', 'Model X', 'electric', 2024, FALSE),
    ('Toyota', 'Corolla', 'oil', 2025, TRUE),
    ('Skoda', 'Octavia', 'diesel', 2015, FALSE),
    ('BMW', '320d', 'diesel', 2016, FALSE),
    ('Volkswagen', 'Golf', 'diesel', 2017, TRUE),
    ('Volkswagen', 'Passat', 'diesel', 2018, FALSE),
    ('Volkswagen', 'Polo', 'oil', 2019, FALSE),
    ('Volkswagen', 'ID.3', 'electric', 2020, TRUE),
    ('Volkswagen', 'ID.4', 'electric', 2021, FALSE),
    ('Tesla', 'Model 3', 'electric', 2022, FALSE),
    ('Tesla', 'Model Y', 'electric', 2023, TRUE),
    ('Tesla', 'Model S', 'electric', 2024, FALSE),
    ('Tesla', 'Model X', 'electric', 2025, FALSE),
    ('Toyota', 'Corolla', 'oil', 2015, TRUE),
    ('Skoda', 'Octavia', 'diesel', 2016, FALSE),
    ('BMW', '320d', 'diesel', 2017, FALSE),
    ('Volkswagen', 'Golf', 'diesel', 2018, TRUE),
    ('Volkswagen', 'Passat', 'diesel', 2019, FALSE),
    ('Volkswagen', 'Polo', 'oil', 2020, FALSE),
    ('Volkswagen', 'ID.3', 'electric', 2021, TRUE),
    ('Volkswagen', 'ID.4', 'electric', 2022, FALSE),
    ('Tesla', 'Model 3', 'electric', 2023, FALSE),
    ('Tesla', 'Model Y', 'electric', 2024, TRUE),
    ('Tesla', 'Model S', 'electric', 2025, FALSE),
    ('Tesla', 'Model X', 'electric', 2015, FALSE),
    ('Toyota', 'Corolla', 'oil', 2016, TRUE),
    ('Skoda', 'Octavia', 'diesel', 2017, FALSE),
    ('BMW', '320d', 'diesel', 2018, FALSE),
    ('Volkswagen', 'Golf', 'diesel', 2019, TRUE),
    ('Volkswagen', 'Passat', 'diesel', 2020, FALSE),
    ('Volkswagen', 'Polo', 'oil', 2021, FALSE),
    ('Volkswagen', 'ID.3', 'electric', 2022, TRUE),
    ('Volkswagen', 'ID.4', 'electric', 2023, FALSE),
    ('Tesla', 'Model 3', 'electric', 2024, FALSE),
    ('Tesla', 'Model Y', 'electric', 2025, TRUE),
    ('Tesla', 'Model S', 'electric', 2015, FALSE),
    ('Tesla', 'Model X', 'electric', 2016, FALSE),
    ('Toyota', 'Corolla', 'oil', 2017, TRUE),
    ('Skoda', 'Octavia', 'diesel', 2018, FALSE),
    ('BMW', '320d', 'diesel', 2019, FALSE);

INSERT INTO customers (name, address) VALUES
    ('Anna Kowalska', 'ul. Marszalkowska 10, Warsaw'),
    ('John Smith', '221B Baker Street, London'),
    ('Maria Garcia', 'Calle Mayor 5, Madrid'),
    ('Hans Mueller', 'Hauptstrasse 12, Berlin'),
    ('Sophie Martin', '12 Rue de Rivoli, Paris'),
    ('Luca Rossi', 'Via Roma 3, Rome'),
    ('Eva Novak', 'Vaclavske namesti 1, Prague'),
    ('Piotr Nowak', 'ul. Florianska 7, Krakow'),
    ('Emma Johansson', 'Drottninggatan 20, Stockholm'),
    ('Liam O''Brien', '14 Grafton Street, Dublin'),
    ('Olga Ivanova', 'Nevsky Prospekt 30, Tallinn'),
    ('Tomas Horvat', 'Ilica 15, Zagreb');

INSERT INTO sales (vehicle_id, customer_id) VALUES
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10),
    (11, 11),
    (12, 12),
    (13, 1),
    (14, 2),
    (15, 3);

INSERT INTO rentals (vehicle_id, customer_id) VALUES
    (16, 4),
    (17, 5),
    (18, 6),
    (19, 7),
    (20, 8),
    (21, 9),
    (22, 10),
    (23, 11),
    (24, 12),
    (25, 1),
    (26, 2),
    (27, 3);
