INSERT INTO reference.customers (customer_type, name, address) VALUES
    ('individual', 'Anna Kowalska', 'ul. Marszalkowska 10, Warsaw'),
    ('individual', 'John Smith', '221B Baker Street, London'),
    ('individual', 'Maria Garcia', 'Calle Mayor 5, Madrid'),
    ('individual', 'Hans Mueller', 'Hauptstrasse 12, Berlin'),
    ('individual', 'Sophie Martin', '12 Rue de Rivoli, Paris'),
    ('individual', 'Luca Rossi', 'Via Roma 3, Rome'),
    ('individual', 'Eva Novak', 'Vaclavske namesti 1, Prague'),
    ('individual', 'Piotr Nowak', 'ul. Florianska 7, Krakow'),
    ('individual', 'Emma Johansson', 'Drottninggatan 20, Stockholm'),
    ('individual', 'Liam O''Brien', '14 Grafton Street, Dublin'),
    ('individual', 'Olga Ivanova', 'Nevsky Prospekt 30, Tallinn'),
    ('individual', 'Tomas Horvat', 'Ilica 15, Zagreb'),
    ('institutional', 'CityShare Mobility Sp. z o.o.', 'ul. Grzybowska 62, Warsaw'),
    ('institutional', 'Nordic Utilities AB', 'Sveavagen 44, Stockholm'),
    ('institutional', 'GreenRoute Logistics GmbH', 'Hafenstrasse 9, Hamburg'),
    ('institutional', 'Metro Taxi Cooperative', 'Via Torino 18, Milan'),
    ('institutional', 'Apex Consulting Group Ltd', '10 Canary Wharf, London');

INSERT INTO reference.individual_customers (customer_id, customer_type, date_of_birth) VALUES
    (1, 'individual', '1965-06-12'),
    (2, 'individual', '1972-11-23'),
    (3, 'individual', '1979-04-06'),
    (4, 'individual', '1986-09-17'),
    (5, 'individual', '1993-02-28'),
    (6, 'individual', '1960-07-11'),
    (7, 'individual', '1967-12-22'),
    (8, 'individual', '1974-05-05'),
    (9, 'individual', '1981-10-16'),
    (10, 'individual', '1988-03-27'),
    (11, 'individual', '1995-08-10'),
    (12, 'individual', '1962-01-21');

INSERT INTO reference.institutional_customers (customer_id, customer_type, tax_id, company_registration_number, contact_person, negotiated_fleet_discount_pct) VALUES
    (13, 'institutional', 'PL5272899999', 'KRS0000654321', 'Marta Wisniewska', NULL),
    (14, 'institutional', 'SE556677889901', '556677-8899', 'Erik Lindqvist', 15),
    (15, 'institutional', 'DE298765432', 'HRB 154321', 'Jonas Becker', 12),
    (16, 'institutional', 'IT09876543210', 'MI-2098765', 'Giulia Bianchi', NULL),
    (17, 'institutional', 'GB123456789', '09876543', 'Oliver Hughes', NULL);

INSERT INTO reference.companies (name, company_type, tax_id, address) VALUES
    ('Northbridge Bank', 'bank', 'PL5251234567', 'ul. Prosta 51, Warsaw'),
    ('Alpine Credit Bank', 'bank', 'ATU12345678', 'Kaerntner Strasse 21, Vienna'),
    ('Baltic Savings Bank', 'bank', 'EE100234567', 'Narva mnt 7, Tallinn'),
    ('EuroDrive Leasing', 'leasing_company', 'DE811234567', 'Friedrichstrasse 88, Berlin'),
    ('Motion Auto Finance', 'leasing_company', 'FR40123456789', '45 Avenue de la Grande Armee, Paris'),
    ('Velo Fleet Leasing', 'leasing_company', 'NL812345678B01', 'Herengracht 120, Amsterdam');

INSERT INTO reference.commercial_policy (id, fleet_minimum_vehicle_count, default_fleet_discount_pct, default_prolongation_period_days) VALUES
    (1, 10, 10, 30);

INSERT INTO reference.factories (name, manufacturer, city, country, opened_year, closed_year, active) VALUES
    ('Mitsubishi Tonsley Park Plant', 'Mitsubishi', 'Adelaide', 'Australia', 1964, 2008, FALSE),
    ('Toyota Altona Plant', 'Toyota', 'Altona', 'Australia', 1994, 2017, FALSE),
    ('Ford Broadmeadows Plant', 'Ford', 'Broadmeadows', 'Australia', 1959, 2016, FALSE),
    ('Holden Elizabeth Plant', 'Holden', 'Elizabeth', 'Australia', 1958, 2017, FALSE),
    ('GM Antwerp Plant', 'General Motors', 'Antwerp', 'Belgium', 1925, 2010, FALSE),
    ('Ford Genk Plant', 'Ford', 'Genk', 'Belgium', 1964, 2014, FALSE),
    ('Renault Vilvoorde Plant', 'Renault', 'Vilvoorde', 'Belgium', 1935, 1997, FALSE),
    ('Fiat Betim Plant', 'Stellantis', 'Betim', 'Brazil', 1976, NULL, TRUE),
    ('Stellantis Windsor Assembly', 'Stellantis', 'Windsor', 'Canada', 1928, NULL, TRUE),
    ('SAIC Volkswagen Anting Plant', 'SAIC Volkswagen', 'Shanghai', 'China', 1985, NULL, TRUE),
    ('Tesla Gigafactory Shanghai', 'Tesla', 'Shanghai', 'China', 2019, NULL, TRUE),
    ('Skoda Mlada Boleslav Plant', 'Skoda', 'Mlada Boleslav', 'Czech Republic', 1905, NULL, TRUE),
    ('Hyundai Nosovice Plant', 'Hyundai', 'Nosovice', 'Czech Republic', 2008, NULL, TRUE),
    ('Renault Billancourt Plant', 'Renault', 'Boulogne-Billancourt', 'France', 1898, 1992, FALSE),
    ('Renault Douai Plant', 'Renault', 'Douai', 'France', 1974, NULL, TRUE),
    ('Toyota Valenciennes Plant', 'Toyota', 'Onnaing', 'France', 2001, NULL, TRUE),
    ('Peugeot Sochaux Plant', 'Stellantis', 'Sochaux', 'France', 1912, NULL, TRUE),
    ('Opel Bochum Plant', 'Opel', 'Bochum', 'Germany', 1962, 2014, FALSE),
    ('Ford Cologne Plant', 'Ford', 'Cologne', 'Germany', 1931, NULL, TRUE),
    ('Automobilwerk Eisenach Plant', 'Automobilwerk Eisenach', 'Eisenach', 'Germany', 1896, 1991, FALSE),
    ('Tesla Gigafactory Berlin-Brandenburg', 'Tesla', 'Gruenheide', 'Germany', 2022, NULL, TRUE),
    ('Audi Ingolstadt Plant', 'Audi', 'Ingolstadt', 'Germany', 1949, NULL, TRUE),
    ('BMW Leipzig Plant', 'BMW', 'Leipzig', 'Germany', 2005, NULL, TRUE),
    ('BMW Munich Plant', 'BMW', 'Munich', 'Germany', 1922, NULL, TRUE),
    ('Opel Russelsheim Plant', 'Opel', 'Russelsheim', 'Germany', 1899, NULL, TRUE),
    ('Mercedes-Benz Sindelfingen Plant', 'Mercedes-Benz', 'Sindelfingen', 'Germany', 1915, NULL, TRUE),
    ('Porsche Zuffenhausen Plant', 'Porsche', 'Stuttgart', 'Germany', 1950, NULL, TRUE),
    ('Volkswagen Wolfsburg Plant', 'Volkswagen', 'Wolfsburg', 'Germany', 1938, NULL, TRUE),
    ('Sachsenring Zwickau Plant', 'Sachsenring', 'Zwickau', 'Germany', 1957, 1991, FALSE),
    ('Volkswagen Zwickau Plant', 'Volkswagen', 'Zwickau', 'Germany', 1990, NULL, TRUE),
    ('Audi Gyor Plant', 'Audi', 'Gyor', 'Hungary', 1993, NULL, TRUE),
    ('Mercedes-Benz Kecskemet Plant', 'Mercedes-Benz', 'Kecskemet', 'Hungary', 2012, NULL, TRUE),
    ('Maruti Suzuki Gurgaon Plant', 'Maruti Suzuki', 'Gurugram', 'India', 1983, NULL, TRUE),
    ('Tata Motors Sanand Plant', 'Tata Motors', 'Sanand', 'India', 2010, NULL, TRUE),
    ('Hindustan Motors Uttarpara Plant', 'Hindustan Motors', 'Uttarpara', 'India', 1948, 2014, FALSE),
    ('Ferrari Maranello Plant', 'Ferrari', 'Maranello', 'Italy', 1943, NULL, TRUE),
    ('Lamborghini Sant Agata Plant', 'Lamborghini', 'Sant Agata Bolognese', 'Italy', 1963, NULL, TRUE),
    ('Fiat Termini Imerese Plant', 'Fiat', 'Termini Imerese', 'Italy', 1970, 2011, FALSE),
    ('Fiat Lingotto Plant', 'Fiat', 'Turin', 'Italy', 1923, 1982, FALSE),
    ('Fiat Mirafiori Plant', 'Fiat', 'Turin', 'Italy', 1939, NULL, TRUE),
    ('Honda Sayama Plant', 'Honda', 'Sayama', 'Japan', 1964, 2021, FALSE),
    ('Honda Suzuka Plant', 'Honda', 'Suzuka', 'Japan', 1960, NULL, TRUE),
    ('Toyota Motomachi Plant', 'Toyota', 'Toyota City', 'Japan', 1959, NULL, TRUE),
    ('Ford Hermosillo Plant', 'Ford', 'Hermosillo', 'Mexico', 1986, NULL, TRUE),
    ('Volkswagen Puebla Plant', 'Volkswagen', 'Puebla', 'Mexico', 1967, NULL, TRUE),
    ('BMW San Luis Potosi Plant', 'BMW', 'San Luis Potosi', 'Mexico', 2019, NULL, TRUE),
    ('GM Silao Assembly', 'General Motors', 'Silao', 'Mexico', 1995, NULL, TRUE),
    ('Renault Tangier Plant', 'Renault', 'Tangier', 'Morocco', 2012, NULL, TRUE),
    ('FSO Zeran Plant', 'FSO', 'Warsaw', 'Poland', 1951, 2011, FALSE),
    ('Dacia Mioveni Plant', 'Dacia', 'Mioveni', 'Romania', 1968, NULL, TRUE),
    ('AZLK Moskvitch Plant', 'AZLK', 'Moscow', 'Russia', 1930, 2010, FALSE),
    ('ZIL Moscow Plant', 'ZIL', 'Moscow', 'Russia', 1916, 2013, FALSE),
    ('AvtoVAZ Togliatti Plant', 'AvtoVAZ', 'Togliatti', 'Russia', 1970, NULL, TRUE),
    ('Zastava Kragujevac Plant', 'Zastava', 'Kragujevac', 'Serbia', 1953, 2008, FALSE),
    ('Volkswagen Bratislava Plant', 'Volkswagen', 'Bratislava', 'Slovakia', 1991, NULL, TRUE),
    ('Jaguar Land Rover Nitra Plant', 'Jaguar Land Rover', 'Nitra', 'Slovakia', 2018, NULL, TRUE),
    ('Kia Zilina Plant', 'Kia', 'Zilina', 'Slovakia', 2006, NULL, TRUE),
    ('Volkswagen Kariega Plant', 'Volkswagen', 'Kariega', 'South Africa', 1951, NULL, TRUE),
    ('BMW Rosslyn Plant', 'BMW', 'Rosslyn', 'South Africa', 1973, NULL, TRUE),
    ('Hyundai Ulsan Plant', 'Hyundai', 'Ulsan', 'South Korea', 1968, NULL, TRUE),
    ('SEAT Martorell Plant', 'SEAT', 'Martorell', 'Spain', 1993, NULL, TRUE),
    ('Volvo Torslanda Plant', 'Volvo Cars', 'Gothenburg', 'Sweden', 1964, NULL, TRUE),
    ('Volvo Uddevalla Plant', 'Volvo Cars', 'Uddevalla', 'Sweden', 1989, 1993, FALSE),
    ('Tofas Bursa Plant', 'Tofas', 'Bursa', 'Turkey', 1971, NULL, TRUE),
    ('Ford Otosan Golcuk Plant', 'Ford Otosan', 'Golcuk', 'Turkey', 2001, NULL, TRUE),
    ('MG Rover Longbridge Plant', 'MG Rover', 'Birmingham', 'United Kingdom', 1905, 2016, FALSE),
    ('Toyota Burnaston Plant', 'Toyota', 'Burnaston', 'United Kingdom', 1992, NULL, TRUE),
    ('Jaguar Browns Lane Plant', 'Jaguar', 'Coventry', 'United Kingdom', 1951, 2005, FALSE),
    ('Peugeot Ryton Plant', 'Peugeot', 'Coventry', 'United Kingdom', 1946, 2007, FALSE),
    ('Standard-Triumph Canley Plant', 'Standard-Triumph', 'Coventry', 'United Kingdom', 1916, 1980, FALSE),
    ('Bentley Crewe Plant', 'Bentley', 'Crewe', 'United Kingdom', 1938, NULL, TRUE),
    ('DeLorean Dunmurry Plant', 'DeLorean Motor Company', 'Dunmurry', 'United Kingdom', 1981, 1982, FALSE),
    ('Lotus Hethel Plant', 'Lotus', 'Hethel', 'United Kingdom', 1966, NULL, TRUE),
    ('Rootes Linwood Plant', 'Rootes Group', 'Linwood', 'United Kingdom', 1963, 1981, FALSE),
    ('MINI Plant Oxford', 'BMW', 'Oxford', 'United Kingdom', 1913, NULL, TRUE),
    ('Land Rover Solihull Plant', 'Jaguar Land Rover', 'Solihull', 'United Kingdom', 1946, NULL, TRUE),
    ('Nissan Sunderland Plant', 'Nissan', 'Sunderland', 'United Kingdom', 1986, NULL, TRUE),
    ('Honda Swindon Plant', 'Honda', 'Swindon', 'United Kingdom', 1992, 2021, FALSE),
    ('GM Arlington Assembly', 'General Motors', 'Arlington', 'United States', 1954, NULL, TRUE),
    ('Tesla Gigafactory Texas', 'Tesla', 'Austin', 'United States', 2022, NULL, TRUE),
    ('Tucker Chicago Plant', 'Tucker', 'Chicago', 'United States', 1947, 1949, FALSE),
    ('Ford River Rouge Complex', 'Ford', 'Dearborn', 'United States', 1917, NULL, TRUE),
    ('Hudson Jefferson Avenue Plant', 'Hudson', 'Detroit', 'United States', 1910, 1954, FALSE),
    ('Packard Automotive Plant', 'Packard', 'Detroit', 'United States', 1903, 1958, FALSE),
    ('NUMMI Fremont Plant', 'New United Motor Manufacturing', 'Fremont', 'United States', 1984, 2010, FALSE),
    ('Tesla Fremont Factory', 'Tesla', 'Fremont', 'United States', 2010, NULL, TRUE),
    ('Toyota Georgetown Plant', 'Toyota', 'Georgetown', 'United States', 1988, NULL, TRUE),
    ('BMW Spartanburg Plant', 'BMW', 'Greer', 'United States', 1994, NULL, TRUE),
    ('Dodge Main Hamtramck Plant', 'Chrysler', 'Hamtramck', 'United States', 1910, 1980, FALSE),
    ('GM Janesville Assembly', 'General Motors', 'Janesville', 'United States', 1919, 2009, FALSE),
    ('AMC Kenosha Main Plant', 'American Motors', 'Kenosha', 'United States', 1902, 1988, FALSE),
    ('Hyundai Alabama Plant', 'Hyundai', 'Montgomery', 'United States', 2005, NULL, TRUE),
    ('Mitsubishi Normal Plant', 'Mitsubishi', 'Normal', 'United States', 1988, 2015, FALSE),
    ('Rivian Normal Plant', 'Rivian', 'Normal', 'United States', 2021, NULL, TRUE),
    ('Ford Twin Cities Assembly Plant', 'Ford', 'Saint Paul', 'United States', 1925, 2011, FALSE),
    ('Nissan Smyrna Plant', 'Nissan', 'Smyrna', 'United States', 1983, NULL, TRUE),
    ('Studebaker South Bend Plant', 'Studebaker', 'South Bend', 'United States', 1902, 1963, FALSE),
    ('GM Spring Hill Manufacturing', 'General Motors', 'Spring Hill', 'United States', 1990, NULL, TRUE),
    ('Mercedes-Benz Tuscaloosa Plant', 'Mercedes-Benz', 'Vance', 'United States', 1997, NULL, TRUE),
    ('Stellantis Warren Truck Assembly', 'Stellantis', 'Warren', 'United States', 1938, NULL, TRUE);
